// SPDX-License-Identifier: MIT OR Apache-2.0

//! Cross-validation tests against `llama.cpp` reference dequantization.
//!
//! These tests load pre-computed fixtures generated by
//! `tests/fixtures/gguf_reference/generate_gguf.py` and compare anamnesis
//! `GGUF` block-quant dequantization output against the `gguf` Python
//! package's `dequantize` function — the official reference implementation
//! from `ggml-org` that mirrors `ggml-quants.c`'s `dequantize_row_*`
//! functions.
//!
//! Each fixture is a 65 536-element slice (2 048 blocks for legacy quants,
//! 256 super-blocks for K-quants) extracted from a real model tensor.
//!
//! Coverage: 10 of 12 production kernels from 3 real models. `Q8_1` and
//! `Q8_K` are not shipped by any real model — they are internal
//! `llama.cpp` activation quant types, already covered by unit tests.

#![cfg(feature = "gguf")]
#![allow(
    clippy::panic,
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::indexing_slicing,
    clippy::as_conversions,
    clippy::wildcard_enum_match_arm
)]

use std::time::Instant;

use anamnesis::{dequantize_gguf_to_bf16, GgufType};

// ---------------------------------------------------------------------------
// Fixture parsing
// ---------------------------------------------------------------------------

/// Binary fixture layout (all little-endian):
///
/// - 4 bytes: `ggml_type` discriminant (`u32`)
/// - 4 bytes: `n_elements` (`u32`)
/// - 4 bytes: raw data byte count (`u32`)
/// - 4 bytes: golden `BF16` byte count (`u32`)
/// - raw quantized block data
/// - expected `BF16` output
struct GgufFixture {
    n_elements: usize,
    raw_data: Vec<u8>,
    expected_bf16: Vec<u8>,
}

fn read_u32_le(data: &[u8], offset: usize) -> u32 {
    let bytes: [u8; 4] = data[offset..offset + 4].try_into().unwrap();
    u32::from_le_bytes(bytes)
}

/// Maps a `ggml_type` discriminant to a [`GgufType`].
///
/// Only covers the 12 dequantizable block types — scalars and
/// `IQ*`/`TQ*`/`MXFP4` are not cross-validated here.
fn gguf_type_from_disc(disc: u32) -> GgufType {
    match disc {
        2 => GgufType::Q4_0,
        3 => GgufType::Q4_1,
        6 => GgufType::Q5_0,
        7 => GgufType::Q5_1,
        8 => GgufType::Q8_0,
        9 => GgufType::Q8_1,
        10 => GgufType::Q2_K,
        11 => GgufType::Q3_K,
        12 => GgufType::Q4_K,
        13 => GgufType::Q5_K,
        14 => GgufType::Q6_K,
        15 => GgufType::Q8_K,
        other => panic!("unknown ggml_type discriminant: {other}"),
    }
}

fn parse_gguf_fixture(data: &[u8], expected_dtype: GgufType) -> GgufFixture {
    let disc = read_u32_le(data, 0);
    let n_elements = read_u32_le(data, 4) as usize;
    let raw_data_len = read_u32_le(data, 8) as usize;
    let golden_len = read_u32_le(data, 12) as usize;

    let actual_dtype = gguf_type_from_disc(disc);
    assert_eq!(
        actual_dtype, expected_dtype,
        "fixture dtype mismatch: expected {expected_dtype:?}, got {actual_dtype:?} (disc={disc})"
    );

    let header_size = 16;
    let raw_start = header_size;
    let golden_start = raw_start + raw_data_len;

    GgufFixture {
        n_elements,
        raw_data: data[raw_start..raw_start + raw_data_len].to_vec(),
        expected_bf16: data[golden_start..golden_start + golden_len].to_vec(),
    }
}

// ---------------------------------------------------------------------------
// BF16 comparison
// ---------------------------------------------------------------------------

/// Compare two `BF16` byte slices, allowing up to `max_ulp_diff` ULP
/// (unit in the last place) difference per element.
///
/// Returns the number of mismatched elements and the maximum ULP diff found.
fn compare_bf16(actual: &[u8], expected: &[u8], max_ulp_diff: u16) -> (usize, u16) {
    assert_eq!(actual.len(), expected.len(), "output length mismatch");
    let mut mismatches = 0;
    let mut max_diff: u16 = 0;

    for (i, (a_pair, e_pair)) in actual
        .chunks_exact(2)
        .zip(expected.chunks_exact(2))
        .enumerate()
    {
        let a_bits = u16::from_le_bytes([a_pair[0], a_pair[1]]);
        let e_bits = u16::from_le_bytes([e_pair[0], e_pair[1]]);

        // Handle NaN: both NaN is a match.
        let a_is_nan = (a_bits & 0x7F80 == 0x7F80) && (a_bits & 0x007F != 0);
        let e_is_nan = (e_bits & 0x7F80 == 0x7F80) && (e_bits & 0x007F != 0);
        if a_is_nan && e_is_nan {
            continue;
        }
        if a_is_nan != e_is_nan {
            mismatches += 1;
            continue;
        }

        let diff = a_bits.abs_diff(e_bits);
        if diff > max_ulp_diff {
            mismatches += 1;
            if i < 5 {
                eprintln!(
                    "  element {i}: actual=0x{a_bits:04X}, expected=0x{e_bits:04X}, diff={diff} ULP"
                );
            }
        }
        if diff > max_diff {
            max_diff = diff;
        }
    }
    (mismatches, max_diff)
}

// ---------------------------------------------------------------------------
// Unified test runner
// ---------------------------------------------------------------------------

fn run_cross_validation(name: &str, data: &[u8], dtype: GgufType, max_ulp: u16) {
    let fixture = parse_gguf_fixture(data, dtype);
    let total = fixture.n_elements;

    // Dequantize with anamnesis and measure time.
    let start = Instant::now();
    let actual = dequantize_gguf_to_bf16(&fixture.raw_data, dtype, fixture.n_elements)
        .expect("dequantization failed");
    let elapsed = start.elapsed();

    assert_eq!(
        actual.len(),
        fixture.expected_bf16.len(),
        "{name}: output length mismatch"
    );

    let (mismatches, max_diff) = compare_bf16(&actual, &fixture.expected_bf16, max_ulp);
    eprintln!(
        "{name}: {total} elements, {mismatches} mismatches, \
         max ULP diff = {max_diff}, anamnesis = {:.1} \u{b5}s",
        elapsed.as_secs_f64() * 1e6
    );
    assert_eq!(
        mismatches, 0,
        "{name}: {mismatches}/{total} elements differ by more than {max_ulp} ULP"
    );
}

// ---------------------------------------------------------------------------
// Legacy quants (block_size=32) — 5 kernels
// ---------------------------------------------------------------------------

#[test]
fn cross_validate_smollm2_q4_0() {
    run_cross_validation(
        "SmolLM2-135M Q4_0 (bartowski)",
        include_bytes!("fixtures/gguf_reference/smollm2_q4_0.bin"),
        GgufType::Q4_0,
        0,
    );
}

#[test]
fn cross_validate_smollm2_q4_1() {
    run_cross_validation(
        "SmolLM2-135M Q4_1 (bartowski)",
        include_bytes!("fixtures/gguf_reference/smollm2_q4_1.bin"),
        GgufType::Q4_1,
        0,
    );
}

#[test]
fn cross_validate_tinyllama_q5_0() {
    run_cross_validation(
        "TinyLlama-1.1B Q5_0 (TheBloke)",
        include_bytes!("fixtures/gguf_reference/tinyllama_q5_0.bin"),
        GgufType::Q5_0,
        0,
    );
}

#[test]
fn cross_validate_smollm2_q5_1() {
    run_cross_validation(
        "SmolLM2-135M Q5_1 (bartowski)",
        include_bytes!("fixtures/gguf_reference/smollm2_q5_1.bin"),
        GgufType::Q5_1,
        0,
    );
}

#[test]
fn cross_validate_smollm2_q8_0() {
    run_cross_validation(
        "SmolLM2-135M Q8_0 (bartowski)",
        include_bytes!("fixtures/gguf_reference/smollm2_q8_0.bin"),
        GgufType::Q8_0,
        0,
    );
}

// ---------------------------------------------------------------------------
// K-quants (block_size=256) — 5 kernels
// ---------------------------------------------------------------------------

#[test]
fn cross_validate_tinyllama_q2_k() {
    run_cross_validation(
        "TinyLlama-1.1B Q2_K (TheBloke)",
        include_bytes!("fixtures/gguf_reference/tinyllama_q2_k.bin"),
        GgufType::Q2_K,
        0,
    );
}

#[test]
fn cross_validate_smollm2_q3_k() {
    run_cross_validation(
        "SmolLM2-135M Q3_K (bartowski)",
        include_bytes!("fixtures/gguf_reference/smollm2_q3_k.bin"),
        GgufType::Q3_K,
        0,
    );
}

#[test]
fn cross_validate_smollm2_q4_k() {
    run_cross_validation(
        "SmolLM2-135M Q4_K (bartowski)",
        include_bytes!("fixtures/gguf_reference/smollm2_q4_k.bin"),
        GgufType::Q4_K,
        0,
    );
}

#[test]
fn cross_validate_smollm2_q5_k() {
    run_cross_validation(
        "SmolLM2-135M Q5_K (bartowski)",
        include_bytes!("fixtures/gguf_reference/smollm2_q5_k.bin"),
        GgufType::Q5_K,
        0,
    );
}

#[test]
fn cross_validate_smollm2_q6_k() {
    run_cross_validation(
        "SmolLM2-135M Q6_K (bartowski)",
        include_bytes!("fixtures/gguf_reference/smollm2_q6_k.bin"),
        GgufType::Q6_K,
        0,
    );
}
