// SPDX-License-Identifier: MIT OR Apache-2.0

//! Cross-validation tests against `PyTorch` reference dequantization.
//!
//! These tests load pre-computed fixtures generated by
//! `tests/fixtures/fp8_reference/generate.py` and compare anamnesis
//! dequantization output against `PyTorch`'s `float8_e4m3fn` → `bfloat16`
//! conversion. Each fixture is a 256×256 slice from a real model.

#![allow(
    clippy::panic,
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::indexing_slicing,
    clippy::as_conversions,
    clippy::wildcard_enum_match_arm
)]

use std::time::Instant;

use anamnesis::{
    dequantize_fp8_to_bf16, dequantize_per_channel_fp8_to_bf16, dequantize_per_tensor_fp8_to_bf16,
    parse_safetensors_header, parse_safetensors_header_from_reader, Dtype, QuantScheme,
};

// ---------------------------------------------------------------------------
// Fixture parsing
// ---------------------------------------------------------------------------

/// Binary fixture layout (all little-endian):
///
/// - 4 bytes: scheme (0 = fine-grained, 1 = per-tensor, 2 = per-channel)
/// - 4 bytes: scale dtype (0 = `F32`, 1 = `BF16`, 2 = `F16`)
/// - 4 bytes: rows (`u32`)
/// - 4 bytes: cols (`u32`)
/// - 4 bytes: weight byte count (`u32`)
/// - 4 bytes: scale byte count (`u32`)
/// - 4 bytes: expected byte count (`u32`)
/// - weight bytes, scale bytes, expected `BF16` bytes
struct Fixture {
    scheme: u32,
    scale_dtype: Dtype,
    rows: usize,
    cols: usize,
    weight_data: Vec<u8>,
    scale_data: Vec<u8>,
    expected_bf16: Vec<u8>,
}

fn read_u32_le(data: &[u8], offset: usize) -> u32 {
    let bytes: [u8; 4] = data[offset..offset + 4].try_into().unwrap();
    u32::from_le_bytes(bytes)
}

fn parse_fixture(data: &[u8]) -> Fixture {
    let scheme = read_u32_le(data, 0);
    let scale_dtype_id = read_u32_le(data, 4);
    let rows = read_u32_le(data, 8) as usize;
    let cols = read_u32_le(data, 12) as usize;
    let weight_len = read_u32_le(data, 16) as usize;
    let scale_len = read_u32_le(data, 20) as usize;
    let expected_len = read_u32_le(data, 24) as usize;

    let header_size = 28;
    let weight_start = header_size;
    let scale_start = weight_start + weight_len;
    let expected_start = scale_start + scale_len;

    let scale_dtype = match scale_dtype_id {
        0 => Dtype::F32,
        1 => Dtype::BF16,
        2 => Dtype::F16,
        other => panic!("unknown scale dtype id: {other}"),
    };

    Fixture {
        scheme,
        scale_dtype,
        rows,
        cols,
        weight_data: data[weight_start..weight_start + weight_len].to_vec(),
        scale_data: data[scale_start..scale_start + scale_len].to_vec(),
        expected_bf16: data[expected_start..expected_start + expected_len].to_vec(),
    }
}

// ---------------------------------------------------------------------------
// BF16 comparison
// ---------------------------------------------------------------------------

/// Compare two `BF16` byte slices, allowing up to `max_ulp_diff` ULP
/// (unit in the last place) difference per element.
///
/// Returns the number of mismatched elements and the maximum ULP diff found.
fn compare_bf16(actual: &[u8], expected: &[u8], max_ulp_diff: u16) -> (usize, u16) {
    assert_eq!(actual.len(), expected.len(), "output length mismatch");
    let mut mismatches = 0;
    let mut max_diff: u16 = 0;

    for (i, (a_pair, e_pair)) in actual
        .chunks_exact(2)
        .zip(expected.chunks_exact(2))
        .enumerate()
    {
        let a_bits = u16::from_le_bytes([a_pair[0], a_pair[1]]);
        let e_bits = u16::from_le_bytes([e_pair[0], e_pair[1]]);

        // Handle NaN: both NaN is a match.
        let a_is_nan = (a_bits & 0x7F80 == 0x7F80) && (a_bits & 0x007F != 0);
        let e_is_nan = (e_bits & 0x7F80 == 0x7F80) && (e_bits & 0x007F != 0);
        if a_is_nan && e_is_nan {
            continue;
        }
        if a_is_nan != e_is_nan {
            mismatches += 1;
            continue;
        }

        let diff = a_bits.abs_diff(e_bits);
        if diff > max_ulp_diff {
            mismatches += 1;
            if i < 5 {
                eprintln!(
                    "  element {i}: actual=0x{a_bits:04X}, expected=0x{e_bits:04X}, diff={diff} ULP"
                );
            }
        }
        if diff > max_diff {
            max_diff = diff;
        }
    }
    (mismatches, max_diff)
}

// ---------------------------------------------------------------------------
// Scale reading helper
// ---------------------------------------------------------------------------

fn read_scalar_scale(data: &[u8], dtype: Dtype) -> f32 {
    match dtype {
        Dtype::F32 => {
            let arr: [u8; 4] = data[..4].try_into().unwrap();
            f32::from_le_bytes(arr)
        }
        Dtype::BF16 => {
            let arr: [u8; 2] = data[..2].try_into().unwrap();
            f32::from_bits(u32::from(u16::from_le_bytes(arr)) << 16)
        }
        Dtype::F16 => {
            let arr: [u8; 2] = data[..2].try_into().unwrap();
            half::f16::from_le_bytes(arr).to_f32()
        }
        _ => panic!("unexpected scale dtype: {dtype}"),
    }
}

// ---------------------------------------------------------------------------
// Unified test runner
// ---------------------------------------------------------------------------

fn run_cross_validation(name: &str, data: &[u8], max_ulp: u16) {
    let fixture = parse_fixture(data);
    let total = fixture.rows * fixture.cols;

    // Dequantize with anamnesis and measure time.
    let start = Instant::now();
    let actual = match fixture.scheme {
        0 => dequantize_fp8_to_bf16(
            &fixture.weight_data,
            &fixture.scale_data,
            fixture.rows,
            fixture.cols,
            fixture.scale_dtype,
        )
        .expect("fine-grained dequant failed"),
        1 => {
            let scale = read_scalar_scale(&fixture.scale_data, fixture.scale_dtype);
            dequantize_per_tensor_fp8_to_bf16(&fixture.weight_data, scale)
                .expect("per-tensor dequant failed")
        }
        2 => dequantize_per_channel_fp8_to_bf16(
            &fixture.weight_data,
            &fixture.scale_data,
            fixture.rows,
            fixture.cols,
            fixture.scale_dtype,
        )
        .expect("per-channel dequant failed"),
        other => panic!("unknown scheme: {other}"),
    };
    let elapsed = start.elapsed();

    assert_eq!(actual.len(), fixture.expected_bf16.len());

    let (mismatches, max_diff) = compare_bf16(&actual, &fixture.expected_bf16, max_ulp);
    eprintln!(
        "{name}: {total} elements, {mismatches} mismatches, \
         max ULP diff = {max_diff}, anamnesis = {:.1} µs",
        elapsed.as_secs_f64() * 1e6
    );
    assert_eq!(
        mismatches, 0,
        "{name}: {mismatches}/{total} elements differ by more than {max_ulp} ULP"
    );
}

// ---------------------------------------------------------------------------
// Fine-grained (3 models)
// ---------------------------------------------------------------------------

#[test]
fn cross_validate_exaone_fine_grained() {
    run_cross_validation(
        "EXAONE fine-grained (BF16 scales)",
        include_bytes!("fixtures/fp8_reference/exaone_fine_grained.bin"),
        1,
    );
}

#[test]
fn cross_validate_qwen3_1_7b_fine_grained() {
    run_cross_validation(
        "Qwen3-1.7B fine-grained (BF16 scales)",
        include_bytes!("fixtures/fp8_reference/qwen3_1_7b_fine_grained.bin"),
        1,
    );
}

#[test]
fn cross_validate_qwen3_4b_fine_grained_f16() {
    run_cross_validation(
        "Qwen3-4B fine-grained (F16 scales)",
        include_bytes!("fixtures/fp8_reference/qwen3_4b_fine_grained_f16.bin"),
        1,
    );
}

// ---------------------------------------------------------------------------
// Per-tensor (3 models)
// ---------------------------------------------------------------------------

#[test]
fn cross_validate_ministral_per_tensor() {
    run_cross_validation(
        "Ministral per-tensor (BF16 scalar)",
        include_bytes!("fixtures/fp8_reference/ministral_per_tensor.bin"),
        1,
    );
}

#[test]
fn cross_validate_llama_static_per_tensor() {
    run_cross_validation(
        "Llama-static per-tensor (BF16 [1])",
        include_bytes!("fixtures/fp8_reference/llama_static_per_tensor.bin"),
        1,
    );
}

#[test]
fn cross_validate_nvidia_llama_per_tensor() {
    run_cross_validation(
        "NVIDIA Llama per-tensor (F32 scalar)",
        include_bytes!("fixtures/fp8_reference/nvidia_llama_per_tensor.bin"),
        1,
    );
}

// ---------------------------------------------------------------------------
// Per-channel (1 model)
// ---------------------------------------------------------------------------

#[test]
fn cross_validate_llama_dynamic_per_channel() {
    run_cross_validation(
        "Llama-dynamic per-channel (BF16 [N,1])",
        include_bytes!("fixtures/fp8_reference/llama_dynamic_per_channel.bin"),
        1,
    );
}

// ---------------------------------------------------------------------------
// Phase 4.8: reader-generic safetensors header parsing
// ---------------------------------------------------------------------------

/// Build a synthetic `.safetensors` buffer that exercises `FineGrainedFp8`
/// scheme detection — `FP8` weight + 2D `_scale_inv` companion + `BF16`
/// passthrough norm. Mirrors the fixture diversity (`FP8` / `GPTQ` / `AWQ`
/// / `BnB`) the existing `*_reference.bin` fixtures cover for
/// dequantization, but produced in-memory because the binary fixtures are
/// raw weight/scale blobs, not real safetensors files. The
/// substrate-equivalence the test asserts is structural: any byte buffer
/// that parses through the slice-based path must parse identically through
/// the reader-based path.
fn build_synthetic_safetensors_buffer() -> Vec<u8> {
    let weight_data: Vec<u8> = vec![0; 16]; // 4 × 4 FP8 = 16 bytes
    let scale_data: Vec<u8> = vec![0; 16]; // 2 × 2 F32 = 16 bytes (fine-grained)
    let norm_data: Vec<u8> = vec![0; 4]; // 2 × BF16 = 4 bytes

    let views = vec![
        (
            "layer.0.weight",
            safetensors::tensor::TensorView::new(
                safetensors::Dtype::F8_E4M3,
                vec![4, 4],
                &weight_data,
            )
            .unwrap(),
        ),
        (
            "layer.0.weight_scale_inv",
            safetensors::tensor::TensorView::new(safetensors::Dtype::F32, vec![2, 2], &scale_data)
                .unwrap(),
        ),
        (
            "model.norm.weight",
            safetensors::tensor::TensorView::new(safetensors::Dtype::BF16, vec![2], &norm_data)
                .unwrap(),
        ),
    ];
    safetensors::tensor::serialize(views, &None).unwrap()
}

/// Phase 4.8 substrate-equivalence: `parse_safetensors_header_from_reader`
/// over an in-memory `Cursor` returns a `SafetensorsHeader` whose every
/// field matches `parse_safetensors_header` over the same bytes. This is
/// the behavioural contract HTTP-range adapters depend on — the substrate
/// (slice vs. cursor vs. range-backed adapter) must not change the
/// metadata.
#[test]
fn parse_safetensors_path_and_reader_agree_on_synthetic_fixture() {
    let buffer = build_synthetic_safetensors_buffer();

    let slice_header = parse_safetensors_header(&buffer).expect("slice parse failed");
    let reader_header = parse_safetensors_header_from_reader(std::io::Cursor::new(&buffer))
        .expect("reader parse failed");

    eprintln!(
        "Synthetic safetensors substrate parity: {} tensors, scheme={:?}",
        reader_header.tensors.len(),
        reader_header.scheme
    );

    assert_eq!(slice_header.scheme, QuantScheme::FineGrainedFp8);
    assert_eq!(slice_header.scheme, reader_header.scheme);
    assert_eq!(slice_header.header_size, reader_header.header_size);
    assert_eq!(slice_header.metadata, reader_header.metadata);
    assert_eq!(slice_header.gptq_config, reader_header.gptq_config);
    assert_eq!(slice_header.awq_config, reader_header.awq_config);
    assert_eq!(slice_header.bnb_config, reader_header.bnb_config);
    assert_eq!(slice_header.tensors.len(), reader_header.tensors.len());

    for (a, b) in slice_header
        .tensors
        .iter()
        .zip(reader_header.tensors.iter())
    {
        assert_eq!(a.name, b.name, "tensor name mismatch");
        assert_eq!(a.dtype, b.dtype, "dtype mismatch for `{}`", a.name);
        assert_eq!(a.shape, b.shape, "shape mismatch for `{}`", a.name);
        assert_eq!(
            a.data_offsets, b.data_offsets,
            "data_offsets mismatch for `{}`",
            a.name
        );
        assert_eq!(a.role, b.role, "role mismatch for `{}`", a.name);
    }
}

/// Phase 4.8 substrate-equivalence on the on-disk path: a real
/// `std::fs::File` handed to `parse_safetensors_header_from_reader`
/// produces the same metadata as `parse_safetensors_header` on the bytes
/// loaded from the same file. Confirms the reader-generic API works on
/// real file reads (not just in-memory `Cursor`s) — the path an
/// `HTTP`-range adapter would resemble after the prefix + `JSON` bytes
/// have been fetched and replayed sequentially.
#[test]
fn parse_safetensors_path_and_reader_agree_on_disk_round_trip() {
    let buffer = build_synthetic_safetensors_buffer();

    let tmp = std::env::temp_dir().join("anamnesis_phase48_disk_roundtrip.safetensors");
    std::fs::write(&tmp, &buffer).expect("write temp safetensors failed");

    let on_disk = std::fs::read(&tmp).expect("read temp safetensors failed");
    let slice_header = parse_safetensors_header(&on_disk).expect("slice parse failed");

    let file = std::fs::File::open(&tmp).expect("open temp safetensors failed");
    let reader_header =
        parse_safetensors_header_from_reader(file).expect("reader parse from file failed");

    std::fs::remove_file(&tmp).ok();

    assert_eq!(slice_header.tensors.len(), reader_header.tensors.len());
    assert_eq!(slice_header.scheme, reader_header.scheme);
    assert_eq!(slice_header.header_size, reader_header.header_size);
    for (a, b) in slice_header
        .tensors
        .iter()
        .zip(reader_header.tensors.iter())
    {
        assert_eq!(a.name, b.name);
        assert_eq!(a.dtype, b.dtype);
        assert_eq!(a.shape, b.shape);
        assert_eq!(a.data_offsets, b.data_offsets);
        assert_eq!(a.role, b.role);
    }
}
